### ISSUE TITLE
/test/continuous/test_ppo.py TypeError on torch.distributions

### ISSUE THREAD

**Issue by nado5** [aai-institute/tianshou#1104]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
    + [ ] design request (i.e. "X should be changed to Y.")
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:

Hi,

I'm currently using Tianshou 1.0.0, python 3.11.8, torch 2.2.2 on Debian 12.
I encounter an issue trying to run the following test script for ppo : https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_ppo.py
I get the following TypeError : test_ppo.<locals>.dist() takes 1 positional argument but 2 were given

How to reproduce error: python test_ppo.py

edit : same thing for mujoco_ppo.py

**Comment by MischaPanch** [comment]
Yes, the examples on the master have been updated to reflect changes that were merged in #1032 .

If you copy the examples from master,  pls install the version currently on master. I will release 1.1.0 soon with the newest changes.

If you want to continue using 1.0.0, you can copy the examples/tests from the corresponding tag instead of from the master branch

**Comment by MischaPanch** [comment]
Btw, it's also mentioned in the changelog - second to last entry in Breaking Changes section :)

**Comment by nado5** [comment]
thanks alot

**Comment by nado5** [comment]
thanks alot
