### ISSUE TITLE
ModuleNotFoundError: No module named 'tianshou.highlevel'

### ISSUE THREAD

**Issue by gitabtion** [aai-institute/tianshou#1188]
I got ``ModuleNotFoundError`` when install by ``pip  install tianshou``
> from tianshou.highlevel.logger import LoggerFactoryDefault
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tianshou.highlevel'

Why not add ``highlevel`` module to ``tianshou/__init__.py``?

**Comment by MischaPanch** [comment]
This is not due to something missing in `__init__.py`. Did you install tianshou 1.0.0 or the version from master? The latter is recommended since quite a lot of improvements have been merged since the last release. New release will be finalized soon

**Comment by opcode81** [comment]
In the Python environment to which you installed tianshou, please do this:

```
import tianshou
print(tianshou.__version__)
```

**Comment by gitabtion** [comment]
@MischaPanch @opcode81 Hi, thanks for your reply! I create a new conda enviroment and it works.

**Comment by strakam** [comment]
@opcode81 @MischaPanch  after running `pip install tianshou` the snippet
```
import tianshou
print(tianshou.__version__)
```
gives `AttributeError: partially initialized module 'tianshou' has no attribute '__version__' (most likely due to a circular import)`.

On the other hand, running this from `master` gives `1.2.0-dev`, so I guess `pip` version is not working yet.

Furthermore, running `High-Level API` exa,[;e from the repos' README gives:
```
      EnvFactoryRegistered(task="CartPole-v1", seed=0, venv_type=VectorEnvType.DUMMY),
TypeError: EnvFactoryRegistered.__init__() missing 2 required keyword-only arguments: 'train_seed' and 'test_seed'
```

I think it is very important to have functional examples in README as it is the first interaction of user with the framework. Having these parts not working discourages new users greatly and by effect, development of the framework will be slower.

**Comment by opcode81** [comment]
The README was not updated to reflect the latest changes, but note that the file [examples/discrete/discrete_dqn_hl.py](https://github.com/thu-ml/tianshou/blob/master/examples/discrete/discrete_dqn_hl.py) that is linked to in the README contains the up-to-date code for the example.

The reason I asked for the version is that `highlevel` was added in 1.0.0, so the OP was most likely using a very old release. If you `pip install tianshou==1.1.0` you should get a working version.

If you want to run an example with any version other than the latest source version, you should take the example not from the current development branch but rather from the tag of the version you are actually using.
