### ISSUE TITLE
ImportError: cannot import name 'ActorCritic' from 'tianshou.utils.net.common'

### ISSUE THREAD

**Issue by PengchengWang** [aai-institute/tianshou#464]
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)

**env**: tianshou 0.4.3

in file test/continuous/test_ppo.py

  ```python
from tianshou.utils.net.common import ActorCritic, Net
  ```
after run `python3 test_ppo.py --render=0.03`, the following error occured:
```bash
Traceback (most recent call last):
  File "test_ppo.py", line 16, in <module>
    from tianshou.utils.net.common import ActorCritic, Net
ImportError: cannot import name 'ActorCritic' from 'tianshou.utils.net.common' (xxxx/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/tianshou/utils/net/common.py)
```
And I **can't find** `ActorCritic` in dir xxxx/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/tianshou.

**Comment by Trinkle23897** [comment]
It is because we haven't published the latest version based on the current master code. I'll fix it today.

Two temporary solutions:
1. install via github: `pip install git+https://github.com/thu-ml/tianshou.git@master --upgrade`
2. use the original library code, check out version 0.4.3 and run that test: `git checkout v0.4.3`

**Comment by Trinkle23897** [comment]
should be fine now :) please re-install via `pip3 install tianshou --upgrade`

**Comment by PengchengWang** [comment]
> should be fine now :) please re-install via `pip3 install tianshou --upgrade`

thx
