### ISSUE TITLE
Visualize result in real time

### ISSUE THREAD

**Issue by caimingxue** [aai-institute/tianshou#482]
Hi, how can you see the results (such as rewards, loss, ...) of the visualization in real-time while training a model? Just like using tensorboard or Visdom. Thanks

**Comment by Trinkle23897** [comment]
I think it has already supported in tianshou for quite a long time. For example, when running `examples/atari/atari_c51.py`, a tensorboard tfevents will be at `log/PongNoFrameskip-v4/c51/` and use `tensorboard --logdir log/PongNoFrameskip-v4/c51/` you'll see the result. Also we support [wandb](https://wandb.ai/). For more information please refer to https://tianshou.readthedocs.io/en/master/tutorials/logger.html

**Comment by Trinkle23897** [comment]
I've fixed this issue in #485 by adding an extra line in `TensorboardLogger.write`:
```python
self.writer.flush()
```
In previous version of tensorboard, the written data is automatically flushed into the disk. <s>But now it needs to manually call `flush` method to sync.</s> It is because the default sync interval is 120s. https://pytorch.org/docs/stable/tensorboard.html

BTW, wandb naturally uploads the log event in real-time.
