### ISSUE TITLE
Is there any bc or gail in the tianshou

### ISSUE THREAD

**Issue by KangOxford** [aai-institute/tianshou#531]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

**Comment by Trinkle23897** [comment]
Behavior cloning can be implemented via offline trainer. A more complex example of Dagger is [here](https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_sac_with_il.py). GAIL hasn't been implemented.

**Comment by KangOxford** [comment]
Behavioral Cloning

[DAgger](https://arxiv.org/abs/1011.0686) with synthetic examples

[Adversarial Inverse Reinforcement Learning](https://arxiv.org/abs/1710.11248) (AIRL)

[Generative Adversarial Imitation Learning](https://arxiv.org/abs/1606.03476) (GAIL)

**Comment by KangOxford** [comment]
> Behavior cloning can be implemented via offline trainer. A more complex example of Dagger is [here](https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_sac_with_il.py). GAIL hasn't been implemented.

https://summerofcode.withgoogle.com/ Would you mind take part in the google summer code program as an orgnization. I am curious about adding the gail into tianshou by this program.

**Comment by Trinkle23897** [comment]
tianshou has successfully applied to 2022
Your application has been submitted successfully, and you will receive a confirmation email soon.

On Mar 6, 2022, you will receive an email letting you know whether or not your application has been accepted.

**Comment by nuance1979** [comment]
> Behavior cloning can be implemented via offline trainer. A more complex example of Dagger is [here](https://github.com/thu-ml/tianshou/blob/master/test/continuous/test_sac_with_il.py). GAIL hasn't been implemented.

Actually I have implemented GAIL and AIRL in tianshou but on Atari envs they didn't seem to help. I understand that they were originally designed for continuous control so it should be benchmarked on Mujoco envs. Now that Mujoco is free, I can try run some experiments on them to make sure the implementation is correct.

**Comment by Ericonaldo** [comment]
Imitation researchers may try this repo? https://github.com/Ericonaldo/ILSwiss 😃

**Comment by Trinkle23897** [comment]
Hello GSoC 2022 Org Admin Applicants,


We are busy reviewing all the GSoC 2022 Org Apps and are finding a large number of organizations that are missing information from their Ideas list. Rather than individually emailing each org separately with issues I am sending an email to all orgs that applied to ask you all to please look at your ideas list and be sure you have done the following things: 


1. Be sure to include whether the project is a 175 hour (medium sized) or 350 hour (large project). If it can be either please state that - per idea. This is missing from about 25% of the org apps right now. Please use the 175 hour and 350 hour designations instead of full time, half time, large, medium, or any other term.


2. Your Ideas Page URL should be accessible to all and not require login. This is the same URL contributors will be using if your org is selected. Test using Chrome Incognito or Firefox Private Browsing modes.


3. As we state in the [Defining a Project Idea List](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list) section of the Mentor guide, please provide the following information for each idea:


a) a project title/description 

b) more detailed description of the project (2-5+ sentences) 

c) expected outcomes 

d) skills required/preferred 

e) possible mentors 

f) expected size of project (175 or 350 hour) 

g) an easy, medium or hard difficulty rating of each project.


4. Some of you are still working on your ideas.  Adding and refining ideas is fine, but we are reviewing them between now and Monday. We can only make decisions based on what we see when we review your application. For example, if you only have 2 ideas when we review your org app, your org will be rejected.


If you want to be selected this year I strongly suggest you make sure your Project Ideas list meets the above requirements ASAP.

**Comment by KangOxford** [comment]
> Imitation researchers may try this repo? https://github.com/Ericonaldo/ILSwiss 😃

It's a good implementation! I have used it before.
