### ISSUE TITLE
Why re-sample next action when getting the target Q-value in SAC?

### ISSUE THREAD

**Issue by alexnikulkov** [aai-institute/tianshou#693]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [X] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [X] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```

When we get the target Q-value for SAC we re-sample the next action and use the Q-value at that action (and next state). https://github.com/thu-ml/tianshou/blob/master/tianshou/policy/modelfree/sac.py#L139
```
      obs_next_result = self(batch, input="obs_next")
      act_ = obs_next_result.act
```
Is there a reason why it's done this way? I'm debugging the learning process and the extra stochasticity from this re-sampling makes the debugging process a bit harder. I was expecting the next action from the replay buffer to be used, something like this:
```
      act_ = batch.act_next
```

**Comment by danagi** [comment]
Hi. Recall that
![MommyTalk1657721646227](https://user-images.githubusercontent.com/10044447/178755279-1c0bf091-d91d-4303-a224-50c4cf56aaaf.png).
So, to get the target Q-value, we need the state-value V(s).

With the use of stochastic gradients, we can estimate it (arxiv:1812.05905) by re-sampling an action from **the current policy** as in soft policy iteration we have
![MommyTalk1657721670888](https://user-images.githubusercontent.com/10044447/178755245-a9942f84-89ec-4e46-8a3c-0c980ba984e5.jpg).

You can't use the action from the replay buffer because it comes from the action distribution of a previous policy.

Note that, there's no such problem in discrete SAC  because we can calculate the state-value exactly by Q-values.
