### ISSUE TITLE
Add AIMstack logger

### ISSUE THREAD

**Issue by jamartinh** [aai-institute/tianshou#776]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [X] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
 
Hi, it would be very nice to have Aimstack logger built in tianshou

[Aim stack](https://aimstack.io/)

**An easy-to-use & supercharged open-source ML experiment tracker**

**Comment by tamohannes** [comment]
Hi @jamartinh, I am Hovhannes from Aim 😊. I will love to help you to work on this integration 🚀
Please feel free to let me know what I can do from my side.

**Comment by MischaPanch** [comment]
Tianshou should rather support any custom logger instead of having a 3-rd party backed in. That being said, of course some standard loggers should be implemented - atm. it's tensorboard and wandb.

I'm gonna close this due to inactivity, if anyone feels like their custom loggers cannot be properly used in tianshou, we can reopen
