### ISSUE TITLE
Question about Her goal setting 

### ISSUE THREAD

**Issue by jaried** [aai-institute/tianshou#798]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
```python
  import tianshou, gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
0.4.11 0.26.2 1.12.1+cu116 1.23.3 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] win32
```
1. `compute_reward_fn function`, is `0` to achieve the goal, `-1` to not reach the goal? 
2.  If the `desired_goal` and `achieved_goal` has 3 goals, can it be set to achieve 1 goal when designing the `env.compute_reward function` ?

**Comment by Trinkle23897** [comment]
@Juno-T can you help answer the above questions? Thanks!

**Comment by Juno-T** [comment]
1. In HER, the rewards in a trajectory must also be updated together with the re-written goal. Behind the scene, the HERReplayBuffer's argument [`compute_reward_fn` function](https://github.com/thu-ml/tianshou/blob/master/tianshou/data/buffer/her.py#L33) is the function used to automatically update the rewards based on the achieved goal and the re-written goal.
Normally, you can plug in the `compute_reward_fn` according to the environment's specification. If the environment you are using doesn't provide such reward calculation function, you need to manually implement one to match the specification of the environment. However, you can also invent such function, e.g. for research purpose.
The `0` and `-1` rewards are probably the most common reward function used in goal-based environment where the agent receives `0` reward if it reaches the goal, and `-1` otherwise. Again, you need to look at the specifiction of the environment you are intended to use.

2. I'm not entirely sure what you mean by having 3 goals. The `compute_reward_fn` takes 2 arguments, `achieved_goal` and `desired_goal` which then can be used to calculate the reward however you want, as long as the shape is correct ([see doc](https://tianshou.readthedocs.io/en/master/api/tianshou.data.html#herreplaybuffer)). I think in your case, you can manually implement the `compute_reward_fn` to calculate the reward based on only the goal you are talking about.

**Comment by jaried** [comment]
According to the demo code: https://github.com/thu-ml/tianshou/blob/master/examples/mujoco/fetch_her_ddpg.py

`desired_goal` and `achieved_goal` have 3 dimensions respectively, in the demo, only 3 goals are satisfied at the same time, and `compute_reward_fn` returns to achieve the goal. 

My question is , if only 1 goal is satisfied, is it feasible to return to achieve the goal?

**Comment by Juno-T** [comment]
The demo code uses [FetchReach environment](https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/main/gymnasium_robotics/envs/fetch/reach.py). The 3 dimensions of the goal refer to the x,y,z coordinates of the gripper. The [original reward calculation](https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/main/gymnasium_robotics/envs/fetch/fetch_env.py#L74) is as mentioned, `0` if the coordinates of the gripper match with the goal coordinates, and `-1` otherwise. It makes sense if you want the agent to learn how to move the gripper to the desired position.

In your case, if you implement the `compute_reward_fn` to calculate the reward based on only 1 dimension, I believe that the agent will be able to learn to move the gripper to match, for example, the x coordinate of the given goal.

**Comment by jaried** [comment]
If my code also uses 3 dimensions of goal, can only 1 dimension meet the `desired_goal` at the same time, and the agent can also learn it?

**Comment by Juno-T** [comment]
If you are intended to make it easier for the agent to learn about the goal by conditioning the reward on fewer dimensions, I think it might work. This is more of a research question that you need to do some experiments to verify it. For example, calculate the reward based on 1 random dimension.

Did I answer your question?

**Comment by jaried** [comment]
I see, thank you for your answer.
