### ISSUE TITLE
How to implement Hierachical RL (HRL)

### ISSUE THREAD

**Issue by oximi123** [aai-institute/tianshou#805]
Assume I have a two-level HRL algorithm, where a upper-level agent decides which sub-task to perform, and the lower-level agents (maybe one agent for one sub-task) can solve the corresponding sub-task. The reward of the upper-level agent is obtained after the sub-task is solved by the lower-level agent. Can you give some guidence about how to implement such idea?

**Comment by Trinkle23897** [comment]
@Juno-T could you help with it?

**Comment by xmzzyo** [comment]
+1, I am also looking for an example about how to implement the hierarchical RL algorithms with Tianshou, e.g., hierarchical DQN.

**Comment by Juno-T** [comment]
I haven't tried doing HRL with tianshou yet. From my experience, HRL is very close to multi-agent RL so my first guess is to look at [multi-agent RL tutorial](https://tianshou.readthedocs.io/en/master/tutorials/tictactoe.html). Two-level HRL is basically two agents working collaboratively. To implement the 'subtask' mechanism, you might want to build a custom environment wrapper where the higher level agent's action (which is the desired subtask) is appended to the original observation so that the lower level agent can take it into account. This environment will trigger the original environment when the action from the lower-level agent is recieved. The wrapped environment can ask for actions from lower-level agent and higher-level agent with different time intervals as well, so that the higher-level agent operates on a longer timeline.

I have tried making a simple library for HRL env wrappper before as well which is called [pyHAM](https://github.com/Juno-T/pyham), but I haven't tried it with tianshou yet and the project was not updated. 

With that being said, if you want more control, for example two agents with different learning algorithm/replay buffer etc., you will need to implement a new HRL trainer (and possibly new collector?).

I have also used [Ray's rllib for HRL](https://docs.ray.io/en/latest/rllib/rllib-env.html#multi-agent-and-hierarchical) before. It is also a modified multi-agent training api with a little more control than tianshou's, I think. You might also want to check it out.
