### ISSUE TITLE
_setup_buf gymnasium compatibility

### ISSUE THREAD

**Issue by ligengen** [aai-institute/tianshou#848]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
Dict space can not be recognized [here](https://github.com/thu-ml/tianshou/blob/c8be85b2407bb3b094be92c7a27657231e143963/tianshou/env/worker/subproc.py#L50)

  ```python
  0.5.0 0.28.1 1.11.0 1.23.5 3.8.15 (default, Nov 24 2022, 15:19:38)
  [GCC 11.2.0] linux
  ```
  ```
  >>> import tianshou as ts
  >>> import gymnasium as gym
  >>> from gym.spaces import Dict, Discrete
  >>> x=Dict({"x": Discrete(1)})
  >>> isinstance(x, gym.spaces.Dict)
  False
  >>> import gym
  >>> from gym.spaces import Dict, Discrete
  >>> x=Dict({"x": Discrete(1)})
  >>> isinstance(x, gym.spaces.Dict)
  True
  ```

**Comment by Trinkle23897** [comment]
Sorry for the late reply.

I think the issue is because you are using gym and gymnasium together. Try the following:
```py
import tianshou as ts
import gymnasium as gym
from gymnasium.spaces import Dict, Discrete

x=Dict({"x": Discrete(1)})
assert isinstance(x, gym.spaces.Dict)
```

`from gym.spaces import Dict, Discrete` imports classes from gym instead of gymnasium, where any of these classes would be different from those imported from gymnasium.

If you are using a 3rd-party env that uses `gym`, feel free to fork the source code and change `import gym` to `import gymnasium as gym` everywhere
