### ISSUE TITLE
cannot visualize result when testing mujoco

### ISSUE THREAD

**Issue by zks204** [aai-institute/tianshou#853]
I installed gym, mujoco version 2.10, with either py37 & py38, pyglet version downgrade to 1.2.4. When testing with trained policy, if I set render=0.03, env.render() will raise NotImplementedError which doesn't allow me to visualize the result. However, if I set render=0 with no visualization, the program runs successfully. Please help take a look, very appreciate!

**Comment by Trinkle23897** [comment]
https://github.com/thu-ml/tianshou/blob/e7c2c3711eb4f4430ff36e6df1cf8630714815ad/examples/mujoco/mujoco_env.py#L13-L37

I guess your program ran into the first case using envpool. EnvPool doesn't support rendering results because of thgoughput concerns. You can either uninstall envpool or change the above code to let it fall into the second case using ShmemVectorEnv.

**Comment by MischaPanch** [comment]
Resolved
